version: "3.7"
services:
  # backend:
  #   build: ./backend
  #   ports:
  #     - "3000:3000"
  # frontend:
  #   build: ./frontend
  #   ports:
      # - "5137:5137"
  db:
    image: postgres
    container_name: transcendence-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - transcendence

networks:
  transcendence:
    name: transcendence
    driver: bridge
