version: "3.7"
services:
  backend:
    build: ./backend
    container_name: transcendence-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST
      - DB_PORT
      - DB_CONNECTION
      - DB_USERNAME
      - DB_PASSWORD
      - DB_DATABASE
      - NEST_API_CLIENT_ID
      - NEST_API_CLIENT_SECRET=
      - NEST_API_CLIENT_URL
      - HOST_FRONT
      - FRONTEND_MFA
      - NEST_API_JWT_SECRET
      - FRONTEND_REDIRECT_MFA
    networks:
      - transcendence
  frontend:
    build: ./frontend
    container_name: transcendence-frontend
    ports:
      - "5173:5173"
    networks:
      - transcendence
  db:
    image: postgres
    container_name: transcendence-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - transcendence

networks:
  transcendence:
    name: transcendence
    driver: bridge
